#!/bin/sh
set -e

cd /Users/johansson044/.dotfiles/config/nvim/vimrc

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in /Users/johansson044/.dotfiles/config/nvim/vimrc/my_configs.vim

set runtimepath+=/Users/johansson044/.dotfiles/config/nvim/vimrc

source /Users/johansson044/.dotfiles/config/nvim/vimrc/vimrcs/basic.vim
source /Users/johansson044/.dotfiles/config/nvim/vimrc/vimrcs/filetypes.vim
source /Users/johansson044/.dotfiles/config/nvim/vimrc/vimrcs/plugins_config.vim
source /Users/johansson044/.dotfiles/config/nvim/vimrc/vimrcs/extended.vim
try
  source /Users/johansson044/.dotfiles/config/nvim/vimrc/my_configs.vim
catch
endtry' > ~/.vimrc

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
